version: '3'
services:
 express_app:
   build:
     context: .
     dockerfile: Dockerfile.express
   ports:
     - "3001:3001"  # Changed from 3000
   depends_on:
     - postgresexpress
 
 postgresexpress:
   image: postgres
   ports:
     - "5433:5432"  # Changed from 5432
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: accounts_db
   volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: